services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles: ["all", "storage", "pg"]
  
  weaviate:
    image: semitechnologies/weaviate:stable-v1.31-28ff7a3
    ports:
      - "8081:8080"  # rest
      - "50051:50051"  # grpc
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-openai'
      CLUSTER_HOSTNAME: 'weaviate-node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    profiles: ["all", "storage", "wv"]

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9090:9090"  # Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data
    profiles: ["all", "storage", "minio"]

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
      KAFKA_CREATE_TOPICS: >
        document-landed:33:1,
        document-landed-dlq:33:1,
        document-stored:33:1,
        document-stored-dlq:33:1,
        document-embedded:33:1,
        document-embedded-dlq:33:1
    volumes:
      - kafka_data:/bitnami/kafka
    profiles: ["all", "event", "kafka"]

  api_document:
    build: ./api_document
    container_name: api_document
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    profiles: ["all", "api"]

  service_ingest_documents:
    build: ./service_ingest_documents
    container_name: service_ingest_documents
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_INPUT_TOPIC: "document-landed"
      KAFKA_OUTPUT_TOPIC: "document-stored"
      KAFKA_GROUP_ID: "ingest-documents-group"
      OBJECT_STORAGE_URL: "http://minio:9000"
      OBJECT_STORAGE_BUCKET: "documents"
      OBJECT_STORAGE_USER: ${MINIO_ROOT_USER}
      OBJECT_STORAGE_PASSWORD: ${MINIO_ROOT_PASSWORD}
    depends_on:
      - kafka
    volumes:
      - .data:/app/.data
    profiles: ["all", "service", "service_ingest_documents"]

  jaeger:
    image: jaegertracing/all-in-one:1.74.0
    container_name: jaeger
    command: ["--span-storage.type=badger"]
    volumes:
      - jaeger_data:/badger
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
    profiles: ["all", "jaeger"]

volumes:
  postgres_data:
  weaviate_data:
  minio_data:
  kafka_data:
  jaeger_data:
